build & push image to dockerhub on pull request for specific branches
ONSdigital/sds pull request #105
Opened 2023-09-05 06:16 UTC by AND-AmmarrHafiz

### Motivation and Context

### What has changed

### How to test?

### Links

### Screenshots (if appropriate):

2023-09-06 09:08 UTC, IsaiahLai111 commented on .github/workflows/pull_request.yml
I am curious whether GCP is able to pull the image tagged with branch name instead of the latest branch within the pipeline. If not, then the pipeline is just testing against the latest branch and cannot serve the testing purpose.

2023-09-11 10:07 UTC, AND-AmmarrHafiz commented on .github/workflows/pull_request.yml
Updated code to test against current branch by pushing docker image with branch name and pulling that image in cloudbuilld.yml 
Also updated push to main to tag image with :main instead of :latest

2023-09-11 12:20 UTC, IsaiahLai111 approved these changes

2023-09-11 15:30 UTC, AND-AmmarrHafiz commented on .github/workflows/lint_and_tests.yml
Done.

2023-09-12 06:27 UTC, tidmanmike approved these changes

2023-09-18 08:19 UTC, JonnyAdcockAND approved these changes

2023-09-18 08:32 UTC, IsaiahLai111 commented on cloudbuild-preprod.yaml
> +      args: [ 'build', '-t', 'europe-west2-docker.pkg.dev/${_PROJECT_ID}/sds/sds-preprod:${SHORT_SHA}', '-t', 'europe-west2-docker.pkg.dev/${_PROJECT_ID}/sds/sds-preprod:latest', '-t', 'europe-west2-
Is the cloud build of the preprod image suppose to be in ons-sds-dns as well?

2023-09-18 10:22 UTC, JonnyAdcockAND requested changes

2023-09-18 10:22 UTC, JonnyAdcockAND commented on .github/workflows/publish-image-on-release.yml
> +      - 'v*' #Match tags starting with 'v'
I think this should be using the `release` action instead see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release. Using the `push` event here will mean we end up having both workflows running at the same time when a tag is created. Also not sure whether the `push` event is triggered if the release is created using github.

2023-09-18 10:22 UTC, JonnyAdcockAND commented on .github/workflows/publish-image-on-release.yml
> +          if: startsWith(github.ref, 'refs/tags/v') && github.ref == 'refs/head/main'
Using the `release` event would avoid having to do this check

2023-09-19 08:54 UTC, JonnyAdcockAND approved these changes

2023-09-19 10:01 UTC, merged