[DO_NOT_MERGE] SSDS-50 Running Uvicorn and completing firebase connectivity
ONSdigital/sds pull request #5
Opened 2023-02-02 13:18 UTC by james-smith-methods

2023-02-06 09:24 UTC, dgnball requested changes
Please can you move any files that aren't part of SDS out of the src folder like scratch.py. You have stated that you need this to get the debugger working, but I would suggest we understand this problem before merging. Please can you also change your code so it passes the lint checks.

2023-02-08 15:15 UTC, tidmanmike commented on src/app.py
> +    data = database.get_data(dataset_id=dataset_id, unit_id=unit_id)
Hi James, could you please add doc-stings to any methods that don't have any. the strand will be as follows. (I haven't had a chance to chat about our ways of working, but will book something in.

"""Summary or Description of the Function
 
 Parameters:
 argument1 (int): Description of arg1
 
 Returns:
 int:Returning value
 
"""

2023-02-08 15:20 UTC, tidmanmike commented on src/database.py
> +        dataset_schema_versions.set({LATEST_VERSION: 1, SURVEY_ID: survey_id})
With moving everything to constants, it feels as if we will the human readable element of what we are trying to achieve is attracted away, however what might be better is to have a class model which will map to these constants to give them context. Happy to discuss this further.

2023-02-09 09:40 UTC, dgnball commented on src/constants.py
> +OK = "OK"
I think the addition of this file reduces readability. Please can you undo this change.

2023-02-09 09:41 UTC, dgnball commented on src/paths.py
> +HEALTHCHECK_PATH = "/healthcheck"
I think the addition of this file reduces readability. Please can you undo this change.

2023-02-09 10:13 UTC, closed without merging