added dataset errors
ONSdigital/sds pull request #56
Opened 2023-04-26 14:51 UTC by Mohammed1804

Updated error handing for endpoints.

2023-04-27 08:29 UTC, IsaiahLai111 requested changes

2023-04-27 08:29 UTC, IsaiahLai111 commented on src/app/app.py
>          return exception_throw.throw_400_incorrect_schema_key_exception()
I have forgotten to add a logger.error() here. May be best to keep exception and log error paired

2023-04-27 08:29 UTC, IsaiahLai111 commented on src/app/app.py
> +        return exception_throw.throw_400_incorrect_key_names_exception()
May be best to add a logger.error() here as well, same as above. Thanks

2023-04-27 09:53 UTC, AND-JAshcroft submitted a review, later dismissed

2023-05-02 15:46 UTC, IsaiahLai111 submitted a review, later dismissed

2023-05-03 10:38 UTC, IsaiahLai111 approved these changes

2023-05-03 10:41 UTC, merged